print("================================")
print("        WELCOME TO BOOKSTORE    ")
print("================================")

print("BookStore application is running!")
print("Welcome to our online bookstore.")
print("Today's featured book: The DevOps Handbook")
print("Price: $29.99")  
print("Search feature is available!")
print("You can search for books by title.")